/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Service liveness */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conflicts/detect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Find the tensions between a bundle's constraints */
    post: operations["detect_conflicts_v1_conflicts_detect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conflicts/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply resolutions and return the resulting generation envelope */
    post: operations["resolve_conflicts_v1_conflicts_resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/kb/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Genres, ratings, budget tiers, territories and archetypes */
    get: operations["read_options_v1_kb_options_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user's profile */
    get: operations["read_me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List your projects */
    get: operations["list_projects_v1_projects_get"];
    put?: never;
    /** Create a project */
    post: operations["create_project_v1_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one project */
    get: operations["read_project_v1_projects__project_id__get"];
    put?: never;
    post?: never;
    /** Delete a project */
    delete: operations["delete_project_v1_projects__project_id__delete"];
    options?: never;
    head?: never;
    /** Update a project */
    patch: operations["update_project_v1_projects__project_id__patch"];
    trace?: never;
  };
  "/v1/projects/{project_id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export a project with its full provenance
     * @description The project as JSON and Markdown, with everything behind it.
     *
     *     Both formats in one response rather than two endpoints, because they are
     *     two renderings of one document and returning them together is what
     *     guarantees they cannot disagree.
     */
    get: operations["export_project_v1_projects__project_id__export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{project_id}/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate plot variants for a resolved bundle
     * @description Run the pipeline. Blocked while any HARD conflict is unresolved.
     *
     *     The order matters. The bundle is detected and resolved first —
     *     deterministic, free, and the step that raises 409 with the blocking
     *     conflicts attached — so a bundle that cannot legally be generated never
     *     reaches the model.
     */
    post: operations["generate_v1_projects__project_id__generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{project_id}/variants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List a project's generated variants */
    get: operations["list_variants_v1_projects__project_id__variants_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/variants/{variant_id}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rate a variant, annotate it, or report a rule as a false positive */
    post: operations["submit_feedback_v1_variants__variant_id__feedback_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActionComplexity
     * @description Staging a budget supports or a genre expects. Ascending permissiveness.
     * @enum {string}
     */
    ActionComplexity:
      | "dialogue_driven"
      | "limited_practical"
      | "moderate_set_pieces"
      | "unrestricted";
    /** ArchetypeOption */
    ArchetypeOption: {
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Min Beats */
      min_beats: number;
    };
    /**
     * AudienceSelection
     * @description The age band the writer intends to reach.
     *
     *     Compared against a classification's ``min_audience_age``. A bundle whose
     *     audience cannot be admitted to its own rating is an arithmetic
     *     contradiction between two of the writer's own inputs, which is why the
     *     rule that catches it is HARD.
     */
    AudienceSelection: {
      /** Max Age */
      max_age: number;
      /** Min Age */
      min_age: number;
    };
    /** BeatOut */
    BeatOut: {
      /** Function */
      function: string;
      /** Index */
      index: number;
      /** Summary */
      summary: string;
    };
    /**
     * BudgetTierOption
     * @description A tier as the wizard shows it.
     *
     *     ``scope`` is included because a writer choosing a tier is choosing a
     *     location count and a speaking-cast ceiling, and a picker that shows only
     *     dollar bands asks them to guess at the thing they actually care about.
     */
    BudgetTierOption: {
      /** Guild Context */
      guild_context: string;
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Max Usd */
      max_usd: number | null;
      /** Min Usd */
      min_usd: number;
      /** Order */
      order: number;
      /** Scope */
      scope: {
        [key: string]: unknown;
      };
    };
    /** ClassificationOption */
    ClassificationOption: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Min Audience Age */
      min_audience_age: number;
    };
    /**
     * Conflict
     * @description One tension between two constraints the writer supplied.
     *
     *     ``explanation`` is already rendered: the knowledge base stores a template,
     *     and the detector substitutes the real values before the conflict is built,
     *     so nothing downstream needs the knowledge base to display it. ``evidence``
     *     keeps those substituted values so a report can be audited without re-running
     *     detection.
     */
    Conflict: {
      /** Evidence */
      evidence?: {
        [key: string]: string;
      };
      /** Explanation */
      explanation: string;
      /** Hard Rationale */
      hard_rationale?: string | null;
      /** Resolutions */
      resolutions: components["schemas"]["ResolutionOption"][];
      /** Rule Id */
      rule_id: string;
      severity: components["schemas"]["Severity"];
      /** Title */
      title: string;
    };
    /**
     * ConflictReportResponse
     * @description A conflict report, with the counts a UI gates on already computed.
     *
     *     ``blocking`` is derived server-side rather than left to the client. It is
     *     the flag that disables the Generate button, and a client that computed it
     *     itself could disagree with the endpoint that enforces it.
     */
    ConflictReportResponse: {
      /** Blocking */
      blocking: boolean;
      bundle: components["schemas"]["ConstraintBundle"];
      /** Conflicts */
      conflicts: components["schemas"]["Conflict"][];
      counts: components["schemas"]["SeverityCounts"];
      /** Kb Version */
      kb_version: string;
      /** Rules Evaluated */
      rules_evaluated: number;
    };
    /**
     * ConstraintBundle
     * @description Everything the writer specified, before any conflict has been detected.
     *
     *     This is the unit of reproducibility. A conflict report is a pure function
     *     of a bundle and a knowledge base version, so the pair is enough to explain
     *     any verdict this system has ever issued.
     */
    ConstraintBundle: {
      audience: components["schemas"]["AudienceSelection"];
      /** Budget Tier Id */
      budget_tier_id: string;
      genre: components["schemas"]["GenreSelection"];
      rating: components["schemas"]["RatingTarget"];
      territories: components["schemas"]["TerritorySet"];
    };
    /**
     * ContentDimension
     * @description The six axes on which genre demand and rating permission are both expressed.
     *
     *     Sharing one scale between what a genre wants and what a board allows is
     *     what lets conflict detection be arithmetic rather than interpretive.
     * @enum {string}
     */
    ContentDimension:
      | "violence"
      | "sexual_content"
      | "language"
      | "thematic_darkness"
      | "drug_use"
      | "horror_intensity";
    /**
     * ContentLevel
     * @description Ordinal content intensity, 0 none to 4 explicit.
     *
     *     Numeric on purpose: ``dimension_exceeds`` is a subtraction. Comparable
     *     across rating systems only through the equivalence table, never directly,
     *     because boards apply different criteria to the same nominal level.
     * @enum {integer}
     */
    ContentLevel: 0 | 1 | 2 | 3 | 4;
    /**
     * ContentThresholds
     * @description A level on each of the six content dimensions.
     *
     *     Used for both halves of a content conflict: a genre's conventional demand
     *     and a classification's permitted ceiling are the same shape, which is what
     *     reduces "does this genre fit this rating" to a comparison per axis.
     */
    ContentThresholds: {
      drug_use: components["schemas"]["ContentLevel"];
      horror_intensity: components["schemas"]["ContentLevel"];
      language: components["schemas"]["ContentLevel"];
      sexual_content: components["schemas"]["ContentLevel"];
      thematic_darkness: components["schemas"]["ContentLevel"];
      violence: components["schemas"]["ContentLevel"];
    };
    /** DetectRequest */
    DetectRequest: {
      bundle: components["schemas"]["ConstraintBundle"];
    };
    /** DimensionCheckOut */
    DimensionCheckOut: {
      /** Dimension */
      dimension: string;
      /** Observed */
      observed: number;
      /** Permitted */
      permitted: number;
      /** Satisfied */
      satisfied: boolean;
    };
    /**
     * ExportBundle
     * @description A project as a self-contained, reproducible document.
     *
     *     Carries the constraint bundle, the resolutions, the envelope and every
     *     version that shaped the output. An export that named only the variants
     *     would be a set of loglines nobody could defend.
     */
    ExportBundle: {
      bundle: components["schemas"]["ConstraintBundle"] | null;
      /** Choices */
      choices: components["schemas"]["ResolutionChoice"][];
      /** Conflicts */
      conflicts: components["schemas"]["Conflict"][];
      envelope: components["schemas"]["GenerationEnvelope"] | null;
      /**
       * Exported At
       * Format: date-time
       */
      exported_at: string;
      /** Kb Version */
      kb_version: string;
      /** Markdown */
      markdown: string;
      project: components["schemas"]["Project"];
      /** Prompt Version */
      prompt_version: string;
      /** Variants */
      variants: components["schemas"]["Variant"][];
    };
    /**
     * FailedVariantOut
     * @description A variant that could not be produced, and why.
     *
     *     Returned alongside the successes rather than collapsing the batch. Naming
     *     the archetype means the caller can say which structure is missing rather
     *     than only that something is.
     */
    FailedVariantOut: {
      /** Archetype Id */
      archetype_id: string;
      /** Error Type */
      error_type: string;
      /** Reason */
      reason: string;
      /** Variant Index */
      variant_index: number;
    };
    /** Feedback */
    Feedback: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** False Positive Rule Id */
      false_positive_rule_id: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Notes */
      notes: string | null;
      /** Rating */
      rating: number | null;
      /**
       * Variant Id
       * Format: uuid
       */
      variant_id: string;
    };
    /**
     * FeedbackRequest
     * @description A rating, a note, or a report that a rule fired wrongly.
     *
     *     The false-positive channel is the research contribution here: risk 1 in the
     *     analysis is that the rule set flags tensions working writers do not
     *     recognise, and without a first-class way to say so that evidence never
     *     reaches the knowledge base.
     */
    FeedbackRequest: {
      /** False Positive Rule Id */
      false_positive_rule_id?: string | null;
      /** Notes */
      notes?: string | null;
      /** Rating */
      rating?: number | null;
    };
    /**
     * GenerateRequest
     * @description Ask for variants inside a bundle the writer has already resolved.
     *
     *     The bundle and the choices are sent together rather than the client
     *     referencing a stored report. A report is a pure function of a bundle and a
     *     knowledge base version, so re-deriving it here costs microseconds and
     *     removes an entire class of bug where the stored report and the submitted
     *     bundle have drifted apart.
     */
    GenerateRequest: {
      bundle: components["schemas"]["ConstraintBundle"];
      /**
       * Choices
       * @default []
       */
      choices: components["schemas"]["ResolutionChoice"][];
      /**
       * Seed
       * @default 0
       */
      seed: number;
      /**
       * Variant Count
       * @default 5
       */
      variant_count: number;
    };
    /**
     * GenerationEnvelope
     * @description The complete, resolved bounds one variant must be generated inside.
     *
     *     Layer 2's output: budget scope bounds, content ceilings reduced to the
     *     strictest applicable across every selected territory, the provenance of
     *     each ceiling, and the guidance the writer's resolutions attached.
     *
     *     It also names the budget tier and genre it was built from. Those are not
     *     bounds, but Layer 3 scores archetypes against them, and an envelope that
     *     could not say what produced it would force every later stage to carry the
     *     bundle alongside it and keep the two in step by hand.
     */
    GenerationEnvelope: {
      /** Budget Tier Id */
      budget_tier_id: string;
      /**
       * Directives
       * @default []
       */
      directives: components["schemas"]["PromptDirective"][];
      genre: components["schemas"]["GenreSelection"];
      /**
       * Guidance
       * @default []
       */
      guidance: string[];
      /**
       * Provenance
       * @default []
       */
      provenance: components["schemas"]["ThresholdSource"][];
      scope: components["schemas"]["ScopeEnvelope"];
      thresholds: components["schemas"]["ContentThresholds"];
    };
    /** GenerationResponse */
    GenerationResponse: {
      envelope: components["schemas"]["GenerationEnvelope"];
      /** Failures */
      failures: components["schemas"]["FailedVariantOut"][];
      run: components["schemas"]["GenerationRun"];
      /** Variants */
      variants: components["schemas"]["Variant"][];
    };
    /** GenerationRun */
    GenerationRun: {
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Elapsed Ms */
      elapsed_ms: number | null;
      /** Failed Count */
      failed_count: number;
      /** Generated Count */
      generated_count: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Kb Version */
      kb_version: string;
      /** Model */
      model: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Prompt Version */
      prompt_version: string;
      /** Requested Count */
      requested_count: number;
      /** Seed */
      seed: number;
      /** Status */
      status: string;
    };
    /** GenreOption */
    GenreOption: {
      /** Hybrid Friendly */
      hybrid_friendly: string[];
      /** Id */
      id: string;
      /** Label */
      label: string;
    };
    /**
     * GenreSelection
     * @description A primary genre and an optional secondary modifier.
     *
     *     The secondary is a modifier rather than an equal partner: hybrid rules read
     *     ``secondary_genre`` separately, and several compound the primary's demands
     *     rather than averaging them.
     */
    GenreSelection: {
      /** Primary */
      primary: string;
      /** Secondary */
      secondary?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Service liveness and version information.
     *
     *     ``kb_version`` is reported because the knowledge base determines every
     *     conflict verdict this service produces. Knowing the service version
     *     without it would not identify the behaviour being observed.
     */
    HealthResponse: {
      /**
       * Environment
       * @enum {string}
       */
      environment: "development" | "test" | "production";
      /** Kb Version */
      kb_version: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * KbOptions
     * @description Everything the constraint wizard needs to render, in one request.
     *
     *     One call rather than five: these are always needed together, and a wizard
     *     that renders its budget step before its genre step has arrived is a wizard
     *     that flickers.
     */
    KbOptions: {
      /** Archetypes */
      archetypes: components["schemas"]["ArchetypeOption"][];
      /** Budget Tiers */
      budget_tiers: components["schemas"]["BudgetTierOption"][];
      /** Genres */
      genres: components["schemas"]["GenreOption"][];
      /** Kb Version */
      kb_version: string;
      /** Rating Systems */
      rating_systems: components["schemas"]["RatingSystemOption"][];
      /** Territories */
      territories: components["schemas"]["TerritoryOption"][];
    };
    /**
     * NarrativeEconomy
     * @description How hard each scene must work.
     *
     *     Deliberately not an :class:`OrdinalVocabulary`: the only rule that reads it
     *     (``high_economy_with_large_cast_demand``) tests equality against ``high``.
     *     Nothing ranks these, so nothing here implies they can be ranked.
     * @enum {string}
     */
    NarrativeEconomy: "high" | "moderate" | "standard" | "relaxed";
    /**
     * PeriodSetting
     * @description When a story may be set. Ascending permissiveness.
     *
     *     ``contemporary_or_recent`` means within roughly thirty years, where costume
     *     and set dressing stay inexpensive.
     * @enum {string}
     */
    PeriodSetting:
      | "contemporary_only"
      | "contemporary_or_recent"
      | "any_with_allocation"
      | "any";
    /**
     * Profile
     * @description The account as the product knows it.
     *
     *     The access token is not here and never will be. It reaches this service in
     *     a header and is used to call the database; putting it in a response body
     *     would put it in browser caches, logs and screenshots.
     */
    Profile: {
      /** Avatar Url */
      avatar_url: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
      /** Id */
      id: string;
    };
    /** Project */
    Project: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Description */
      description?: string | null;
      /** Title */
      title: string;
    };
    /** ProjectList */
    ProjectList: {
      /** Projects */
      projects: components["schemas"]["Project"][];
      /** Total */
      total: number;
    };
    /**
     * ProjectUpdate
     * @description A partial update. Every field optional; omitted means unchanged.
     *
     *     Distinct from :class:`ProjectCreate` so that omitting a title on a PATCH is
     *     "leave it alone" rather than "clear it", which a shared model could not
     *     express.
     */
    ProjectUpdate: {
      /** Description */
      description?: string | null;
      /** Status */
      status?: string | null;
      /** Title */
      title?: string | null;
    };
    /**
     * PromptDirective
     * @description One machine-readable constraint, ready to be rendered into a prompt.
     *
     *     Deliberately a key and a value rather than a sentence. Free prose in a
     *     prompt fragment would be a second, untested statement of the constraints
     *     that could drift from the envelope it claims to describe.
     */
    PromptDirective: {
      /** Key */
      key: string;
      /** Value */
      value: string;
    };
    /** RatingSystemOption */
    RatingSystemOption: {
      /** Classifications */
      classifications: components["schemas"]["ClassificationOption"][];
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Territory */
      territory: string;
    };
    /**
     * RatingTarget
     * @description The classification being aimed at, qualified by its system.
     *
     *     A classification id is only meaningful inside its system -- ``u_a`` means
     *     nothing without CBFC -- so the two travel together and are never split.
     */
    RatingTarget: {
      /** Classification */
      classification: string;
      /** System */
      system: string;
    };
    /**
     * ResolutionChoice
     * @description The writer's answer to one conflict.
     */
    ResolutionChoice: {
      /** Resolution Id */
      resolution_id: string;
      /** Rule Id */
      rule_id: string;
    };
    /**
     * ResolutionDelta
     * @description What a chosen resolution actually changed.
     *
     *     Recorded per choice so the audit trail shows the movement, not just the
     *     intent. ``from_level`` and ``to_level`` are populated only for clamps;
     *     an acknowledgement moves nothing and says so by leaving them unset.
     */
    ResolutionDelta: {
      dimension?: components["schemas"]["ContentDimension"] | null;
      effect_kind: components["schemas"]["ResolutionEffectKind"];
      from_level?: components["schemas"]["ContentLevel"] | null;
      /** Guidance */
      guidance?: string | null;
      /** Resolution Id */
      resolution_id: string;
      /** Rule Id */
      rule_id: string;
      to_level?: components["schemas"]["ContentLevel"] | null;
    };
    /**
     * ResolutionEffect
     * @description How choosing a resolution moves the bundle, if it moves it at all.
     *
     *     A resolution with no effect is legitimate and common: it records that the
     *     writer saw the tension and chose to proceed, which is the whole point of
     *     the SOFT tier.
     */
    ResolutionEffect: {
      dimension?: components["schemas"]["ContentDimension"] | null;
      /** Guidance */
      guidance?: string | null;
      kind: components["schemas"]["ResolutionEffectKind"];
    };
    /**
     * ResolutionEffectKind
     * @description What choosing a resolution does to the bundle.
     *
     *     ``ACKNOWLEDGE_RELAXATION`` records the tension without moving any bound,
     *     which is why a resolution may legitimately leave the numbers unchanged.
     * @enum {string}
     */
    ResolutionEffectKind:
      | "clamp_dimension_to_permitted"
      | "acknowledge_relaxation"
      | "requires_bundle_change";
    /**
     * ResolutionOption
     * @description One way out of a conflict, offered to the writer.
     *
     *     ``description`` is phrased in production terms -- what actually changes on
     *     the page -- because a resolution the writer cannot picture is not a choice
     *     they can make.
     */
    ResolutionOption: {
      /** Description */
      description: string;
      effect?: components["schemas"]["ResolutionEffect"] | null;
      /** Id */
      id: string;
      /** Label */
      label: string;
    };
    /** ResolveRequest */
    ResolveRequest: {
      bundle: components["schemas"]["ConstraintBundle"];
      /**
       * Choices
       * @default []
       */
      choices: components["schemas"]["ResolutionChoice"][];
    };
    /**
     * ResolveResponse
     * @description The resolved bundle and the envelope it produces.
     *
     *     Both, because they answer different questions: the deltas say what the
     *     writer's choices changed, and the envelope says what the generator will
     *     actually be held to.
     */
    ResolveResponse: {
      bundle: components["schemas"]["ConstraintBundle"];
      /** Choices */
      choices: components["schemas"]["ResolutionChoice"][];
      /** Deltas */
      deltas: components["schemas"]["ResolutionDelta"][];
      envelope: components["schemas"]["GenerationEnvelope"];
      /** Kb Version */
      kb_version: string;
      original: components["schemas"]["ConstraintBundle"];
      /** Remaining Conflicts */
      remaining_conflicts: components["schemas"]["Conflict"][];
    };
    /** SatisfactionOut */
    SatisfactionOut: {
      /** Dimension Checks */
      dimension_checks: components["schemas"]["DimensionCheckOut"][];
      /** Satisfied */
      satisfied: boolean;
      /** Scope Checks */
      scope_checks: components["schemas"]["ScopeCheckOut"][];
      /** Violations */
      violations: string[];
    };
    /** ScopeCheckOut */
    ScopeCheckOut: {
      /** Limit */
      limit: number | null;
      /** Observed */
      observed: number;
      /** Parameter */
      parameter: string;
      /** Satisfied */
      satisfied: boolean;
    };
    /**
     * ScopeEnvelope
     * @description The production bounds a story must fit inside.
     *
     *     ``max_locations`` and ``max_named_characters`` are optional because the
     *     studio tier genuinely has no budget-imposed ceiling; it is bounded by genre
     *     convention instead. ``None`` states that, where an invented large number
     *     would look like knowledge the knowledge base does not have.
     */
    ScopeEnvelope: {
      action_complexity: components["schemas"]["ActionComplexity"];
      /** Max Locations */
      max_locations?: number | null;
      /** Max Named Characters */
      max_named_characters?: number | null;
      narrative_economy: components["schemas"]["NarrativeEconomy"];
      period_setting: components["schemas"]["PeriodSetting"];
      vfx_complexity: components["schemas"]["VfxComplexity"];
    };
    /**
     * Severity
     * @description What a detected conflict is permitted to do to the user.
     *
     *     Not ordinal: nothing compares severities by position, and the tiering is a
     *     policy about interruption rather than a scale. HARD blocks generation and
     *     is reserved for combinations no narrative can satisfy. SOFT proceeds after
     *     explicit acknowledgement. ADVISORY is informational. The split exists so a
     *     false positive never silently blocks an experienced writer.
     * @enum {string}
     */
    Severity: "HARD" | "SOFT" | "ADVISORY";
    /** SeverityCounts */
    SeverityCounts: {
      /** Advisory */
      advisory: number;
      /** Hard */
      hard: number;
      /** Soft */
      soft: number;
    };
    /** TerritoryOption */
    TerritoryOption: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Rating System */
      rating_system: string;
    };
    /**
     * TerritorySet
     * @description The territories a production intends to release in.
     *
     *     Order is not significant, but it is preserved and duplicates are rejected,
     *     so that two bundles naming the same territories differently still compare
     *     and hash alike after normalisation by the caller.
     */
    TerritorySet: {
      /** Ids */
      ids: string[];
    };
    /**
     * ThresholdSource
     * @description Why one content ceiling is what it is.
     *
     *     Provenance is not decoration. The system's claim is that a variant was
     *     verified against a stated envelope, and a ceiling nobody can trace is a
     *     number the writer has to take on faith. Recording which board or statute
     *     produced each level is what makes the envelope auditable.
     */
    ThresholdSource: {
      /** Authority */
      authority: string;
      /** Detail */
      detail?: string | null;
      dimension: components["schemas"]["ContentDimension"];
      level: components["schemas"]["ContentLevel"];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** Variant */
    Variant: {
      /** Archetype Id */
      archetype_id: string;
      /** Beats */
      beats: components["schemas"]["BeatOut"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Favourite */
      favourite: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Locations */
      locations: string[];
      /** Logline */
      logline: string;
      /** Named Characters */
      named_characters: string[];
      /** Notes */
      notes: string | null;
      provenance: components["schemas"]["VariantProvenanceOut"];
      /** Relaxations */
      relaxations: string[];
      satisfaction: components["schemas"]["SatisfactionOut"];
      /** Surfaceable */
      surfaceable: boolean;
      /** Title */
      title: string;
      /** Variant Index */
      variant_index: number;
      /** Verdicts */
      verdicts: {
        [key: string]: string;
      };
    };
    /** VariantList */
    VariantList: {
      /** Total */
      total: number;
      /** Variants */
      variants: components["schemas"]["Variant"][];
    };
    /**
     * VariantProvenanceOut
     * @description What produced this variant.
     *
     *     Every field is here so a concept can be reproduced or explained months
     *     later. A variant that cannot name its inputs is not a research artefact.
     */
    VariantProvenanceOut: {
      /** Archetype Id */
      archetype_id: string;
      /** Attempts */
      attempts: number;
      /** Kb Version */
      kb_version: string;
      /** Model */
      model: string;
      /** Prompt Version */
      prompt_version: string;
      /** Repaired */
      repaired: boolean;
      /** Seed */
      seed: number;
    };
    /**
     * VfxComplexity
     * @description Visual effects a budget permits or a genre expects. Ascending permissiveness.
     * @enum {string}
     */
    VfxComplexity:
      "none" | "practical_only" | "limited_digital" | "unrestricted";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  detect_conflicts_v1_conflicts_detect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DetectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConflictReportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolve_conflicts_v1_conflicts_resolve_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolveResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_options_v1_kb_options_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KbOptions"];
        };
      };
    };
  };
  read_me_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
    };
  };
  list_projects_v1_projects_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_project_v1_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_project_v1_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_project_v1_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_project_v1_projects__project_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_project_v1_projects__project_id__export_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportBundle"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_v1_projects__project_id__generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenerationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_variants_v1_projects__project_id__variants_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VariantList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_feedback_v1_variants__variant_id__feedback_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        variant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Feedback"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
