#!/usr/bin/env bash
#
# Fails if the vendored shadcn primitives were edited.
#
# `apps/web/components/ui/` is not our code. It is generated by the shadcn CLI
# and owned by it: every customisation must flow through props, `className` or
# a wrapper in `components/features/`, so that re-running `shadcn add` is a
# no-op and an upgrade never silently discards someone's restyling.
#
# Two files carry a sanctioned local edit, made when they were first vendored:
# `sonner.tsx` and `dropdown-menu.tsx` each have a one-line type-compatibility
# shim for `exactOptionalPropertyTypes`, which this workspace enables and
# shadcn does not write for. Both change no behaviour and carry a "Re-apply
# after a shadcn upgrade" comment.
#
# This script does not police those two lines — it compares against the merge
# base, so they read as part of the committed baseline rather than as a change.
# What protects them is `pnpm typecheck`: an upgrade that reverts either shim
# fails it immediately, naming the file. This script's job is the other
# direction — stopping anyone editing a primitive from here on.
#
# Usage:
#   scripts/check-ui-primitives.sh              # compare against origin/main
#   BASE_REF=<ref> scripts/check-ui-primitives.sh
#
# Adding a new primitive is not an edit. `shadcn add <name>` creates a new file
# and this script only objects to changes in files that already existed.

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

readonly UI_DIR="apps/web/components/ui"

if [ ! -d "$UI_DIR" ]; then
  echo "check-ui-primitives: $UI_DIR does not exist yet — nothing to guard"
  exit 0
fi

# Resolve the branch point. In CI the base is supplied; locally, fall back to
# whichever main reference exists so the script is useful before a push.
base="${BASE_REF:-}"
if [ -z "$base" ]; then
  for candidate in origin/main main; do
    if git rev-parse --verify --quiet "$candidate" >/dev/null; then
      base="$candidate"
      break
    fi
  done
fi

if [ -z "$base" ]; then
  echo "check-ui-primitives: no base reference to compare against; skipping"
  exit 0
fi

merge_base="$(git merge-base "$base" HEAD 2>/dev/null || echo "$base")"

# --diff-filter=M: modifications only. Added files are new primitives, which is
# the supported way to use shadcn; deletions are a component being dropped.
modified="$(git diff --name-only --diff-filter=M "$merge_base" -- "$UI_DIR" 2>/dev/null || true)"

if [ -z "$modified" ]; then
  echo "check-ui-primitives: clean (no vendored primitive was modified)"
  exit 0
fi

echo "check-ui-primitives: vendored shadcn primitives were modified"
echo
echo "$modified" | sed 's/^/    /'
echo
cat <<'MESSAGE'
components/ui/ is generated by the shadcn CLI and must stay as it generated it.

  - Need different styling?    Pass className, or wrap it in
                               components/features/ and style the wrapper.
  - Need different behaviour?  Pass props. If the primitive cannot express it,
                               compose it rather than editing it.
  - Need a new primitive?      pnpm dlx shadcn@latest add <name>. Adding a file
                               is fine; this guard only objects to edits.

The two pre-existing exactOptionalPropertyTypes shims in sonner.tsx and
dropdown-menu.tsx are the only sanctioned local edits. See the header of this
script.

If you are re-applying one of those after a shadcn upgrade, that is the one
case where this failure is expected: say so in the commit message.
MESSAGE
exit 1
