#!/usr/bin/env bash
#
# Rejects AI-agent attribution in commit metadata.
#
# CLAUDE.md section 6 requires every commit to be authored by the repository
# owner alone, with no Co-Authored-By trailers and no AI tool named as an
# author or contributor. This script enforces that in CI and can be run
# locally over any commit range.
#
# Usage: check-authorship.sh [<base-ref> <head-ref>]
#        defaults to the last 20 commits when no range is given.

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

if [ "$#" -eq 2 ]; then
  RANGE="$1..$2"
else
  RANGE="HEAD~20..HEAD"
  git rev-parse HEAD~20 >/dev/null 2>&1 || RANGE="HEAD"
fi

# Names that must never appear as an author, co-author or trailer.
FORBIDDEN='Co-Authored-By|Co-authored-by|co-authored-by|Anthropic|Claude|DeepSeek|Copilot|ChatGPT|OpenAI|Generated with|generated by AI|AI-generated'

# `CLAUDE.md` is this repository's operating manual and is referenced by name
# in commit bodies legitimately. Strip the filename before matching so that
# citing the file is not mistaken for crediting a tool.
ALLOWED_LITERALS='CLAUDE\.md'

failures=0

while IFS= read -r sha; do
  [ -z "$sha" ] && continue
  metadata="$(git log -1 --format='%an%n%ae%n%cn%n%ce%n%B' "$sha" | sed -E "s/${ALLOWED_LITERALS}//g")"
  if echo "$metadata" | grep -Eiq "$FORBIDDEN"; then
    if [ "$failures" -eq 0 ]; then
      echo "check-authorship: forbidden attribution found"
      echo
    fi
    failures=1
    echo "  commit $(git log -1 --format='%h %s' "$sha")"
    echo "$metadata" | grep -Ei "$FORBIDDEN" | sed 's/^/    /'
    echo
  fi
done < <(git rev-list "$RANGE" 2>/dev/null)

if [ "$failures" -eq 1 ]; then
  cat <<'MESSAGE'
Every commit must be authored by Samarth D Kolur <samarthdkolur1@gmail.com>
and must not name any AI tool or agent as an author or contributor.

Rewrite the offending commits:

  git rebase -i <base>        # reword the messages
  git commit --amend --author="Samarth D Kolur <samarthdkolur1@gmail.com>"

See CLAUDE.md section 6.
MESSAGE
  exit 1
fi

echo "check-authorship: clean ($RANGE)"
exit 0
